version: '2'
services:
  server:
    image: personal_admin.server:lastest
    container_name: personal_admin.server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    volumes:
    - ".:/app"
  
  database:
    image: mysql:8
    container_name: personal_admin.database
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=personaladmin
    volumes:
    - "./provision/database/structure.sql:/docker-entrypoint-initdb.d/database.sql"
    - "./provision/database/structure.sql:/docker-entrypoint-initdb.d/fixtures.sql"